#!/usr/bin/env sh

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config window_shadow                on
yabai -m config insert_feedback_color        0xaad75f5f
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  12
yabai -m config bottom_padding               12
yabai -m config left_padding                 12
yabai -m config right_padding                12
yabai -m config window_gap                   06

# Spaces
yabai -m space 1 --label music
yabai -m space 2 --label chat
yabai -m space 3 --label browser
yabai -m space 4 --label code
yabai -m space 5 --label terminal

# App rules
yabai -m rule --add app="^Terminal$" space=5
yabai -m rule --add app="^Google Chrome$" space=3
yabai -m rule --add app="^Spotify$" space=1
yabai -m rule --add app="^TeamSpeak 3$" space=2
yabai -m rule --add app="^Slack$" space=2
yabai -m rule --add app="^Discord$" space=2
yabai -m rule --add app="^Visual Studio Code$" space=4
yabai -m rule --add app="^Code$" space=4
yabai -m rule --add app="^Finder$" space=6


echo "yabai configuration loaded.."